sudo: required

services:
  - docker

env:
  global:
    - PIGPIO_GROUP="com/github/jw3"
    - PIGPIO_NAME="pigpio-jna"
    - PIGPIO_VERSION="0.3-SNAPSHOT"
    - PIGPIO_ARTIFACT="$PIGPIO_GROUP/$PIGPIO_NAME/$PIGPIO_VERSION/$PIGPIO_NAME-$PIGPIO_VERSION"
  
script:
  - > 
      docker run -v "$TRAVIS_BUILD_DIR:/data" jwiii/jnaerator:0.12 
      java -jar jnaerator.jar 
      -mode StandaloneJar -runtime JNA 
      -jar "/data/build/$PIGPIO_ARTIFACT.jar" 
      /data/pigpio/pigpio.h
  - sudo chown -R travis:travis "$TRAVIS_BUILD_DIR"
  - cp pom.xml "$TRAVIS_BUILD_DIR/build/$PIGPIO_ARTIFACT.pom"
  - sed "s#PIGPIO_VERSION#$PIGPIO_VERSION#" -i "$TRAVIS_BUILD_DIR/build/$PIGPIO_ARTIFACT.pom"
  - ls -al "$TRAVIS_BUILD_DIR/build/$PIGPIO_GROUP/$PIGPIO_NAME/$PIGPIO_VERSION"
  
deploy:
  provider: bintray
  file: "bintray.json"
  user: "jw3"
  key: "$BINTRAY_API_KEY"
  on:
    tags: true
